---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-apicomms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-csi
