---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-new
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi